os: Visual Studio 2015
platform:
  - x64
  - x86
configuration:
  - Release
matrix:
  fast_finish: true

environment:
  # Prebuild S3 keys
  node_pre_gyp_accessKeyId:
    secure: fA8ogg68+lo8W2gqdyINqRWGCRmpnXuP7ZhqxALG38I=
  node_pre_gyp_secretAccessKey:
    secure: jepVHzuEjGj5OSmBYDBBC/fj7fp2DhkBob7rHLvPKza4CyZUGP7y6WxO/6XLO0e7
  matrix:
    - nodejs_version: 10
      msvs_toolset: 14
    - nodejs_version: 11
      msvs_toolset: 14
    - nodejs_version: 12
      msvs_toolset: 14
    - nodejs_version: 13
      msvs_toolset: 14
    - nodejs_version: 14
      msvs_toolset: 14

install:
  - .\scripts\winci.bat

build: OFF
test: OFF
deploy: OFF
